### ISSUE TITLE
Documentation for undoItem and redoItem is incorrect

### ISSUE THREAD

**Issue by toolness** [ProseMirror/prosemirror-menu#12]
Hello! I've just started using the TypeScript annotations for this module, which were auto-generated from the getdocs-style documentation, and I was having problems using `undoItem` and `redoItem`. I *think* this is because both of these symbols are defined as follows:

```js
// :: (Object) → MenuItem
```

However, in reality it seems they aren't actually functions that return `MenuItem`s, but rather that they *are* `MenuItem`s themselves. Aside from being confusing to readers--the README has similar documentation, I'm not sure if it's auto-generated from getdocs too--it also trips up the auto-generated TypeScript annotations, which requires me to use a type assertion to override it (e.g. `undoItem as any as MenuItem`).

In any case, if this is indeed a mistake in the docs, and not some kind of noobish mistake I've made myself, I'm happy to submit a PR to fix things on this end, just let me know!

Thanks again for making this module, and ProseMirror in general.

**Comment by marijnh** [comment]
Oh, right, those were out of date. Fixed by attached patch

**Comment by toolness** [comment]
Oh cool, thanks!
