### ISSUE TITLE
render isn't recognized as one of the three MenuItem spec options

### ISSUE THREAD

**Issue by adamdonahue** [ProseMirror/prosemirror-menu#13]
![image](https://user-images.githubusercontent.com/2406542/34970204-04eddb9e-fa41-11e7-9315-a005811474dc.png)

The docs above indicate that defining either a label, an icon, _or_ a render method should be sufficient for a MenuItem.  And yet after upgrading from 0.21 to 0.24 all our renderable menu items are now resulting in an error:

![image](https://user-images.githubusercontent.com/2406542/34970233-2c4fa32a-fa41-11e7-981a-bb580f5aa7da.png)

I didn't see anything in the changelog indicating this new behavior, but I'm surprised nobody has reported it before.  Is this a regression?

**Comment by adamdonahue** [comment]
Also note that the MenuElement interface definition of `render` isn't consistent with the MenuItem definition.  So this is confusing all around:

- Is render supported in MenuItem now, at all?
- If it is, should it return a dom element alone (as the docs still indicate)?
- Or should it return an object with a dom property and an update one.  In that case, is there a default, and reasonable, update function?

I was able to "fix" this (assuming it's not just a mistake on my part) locally by check for render in addition to label and icon, and having render of the item return a single DOM element, but this is just a quick-and-dirty fix.

**Comment by marijnh** [comment]
Why are you using 0.24 when there's a 1.0.1? That one should have docs that are consistent with its code. And yeah, using `dom` and `update` is how the menu works now.

**Comment by adamdonahue** [comment]
The code looked the same, but I'll give it a shot.

**Comment by adamdonahue** [comment]
Nope, that didn't work (despite following the documentation).  I hadn't noticed the experimental nature of this repository, though, so we'll just clone and work on our own customized implementation.  Thanks.
