### ISSUE TITLE
The documentation for the Fragment class does have information about the content property

### ISSUE THREAD

**Issue by sunsande** [ProseMirror/prosemirror-menu#29]
The documentation for the `Fragment` class (from the `prosemirror-model`  core module) does not contain information about the `content` property.

I suppose that an automated tool is used to create the documentation from the comments in the source code and in the source code there is no any comment about the content:
```
export class Fragment {
  constructor(content, size) {
    this.content = content                                                   <========== :: content comment is missing =====
    // :: number
    // The size of the fragment, which is the total of the size of its
    // content nodes.
    this.size = size || 0
```

Best regards

**Comment by marijnh** [comment]
Intentionally, because it's not public.

**Comment by sunsande** [comment]
(sorry if I overlook something)
but `size` is also not public in the Fragment class and still has comment and is present in the documentation.

Why would content be not public? If one wants to find a `node` in a `fragment` should one use a loop through 0 to `childCount - 1` and `Fragment.child(index)` ? Or what would be the proper way to do that ? (forEach would iterate through all of the `nodes` and sometimes one would want break early)

**Comment by marijnh** [comment]
The comments _are_ what defines which properties are public.

> If one wants to find a node in a fragment should one use a loop through 0 to childCount - 1 and Fragment.child(index) ? 

Yes.

**Comment by sunsande** [comment]
Thank you.
Just one more question: what is the difference between `Fragment.childCount` and `Fragmen.size`?
