### ISSUE TITLE
Pasting clipboard data raises exception in IE11

### ISSUE THREAD

**Issue by 1999** [ProseMirror/prosemirror-menu#6]
Here's the short video:

![](https://gifyu.com/images/FAB-2147_2.gif)

It seems like the error is happening in this peace of code: https://github.com/ProseMirror/prosemirror-menu/blob/109cd68d32bfdd5fddc04359dd15c6c7b80a126a/src/menubar.js#L52
Transpiler converts it to:

```javascript
this.scrollFunc = function () {
      if (!this$1.editor.root.contains(this$1.wrapper))
        { window.removeEventListener("scroll", this$1.scrollFunc) }
      else
        { this$1.updateFloat() }
    }
```

And it's not the thing IE expects

**Comment by marijnh** [comment]
This was already fixed. Upgrade to prosemirror-menu 0.17.1

**Comment by 1999** [comment]
Does the editor on prosemirror.net use the newest version of prosemirror-menu? I can reproduce the error in the editor there.

**Comment by marijnh** [comment]
It was using the old one, but I just upgraded it.

**Comment by 1999** [comment]
👍
